name: Pack

on:
  push:
    branches: [ "action/pack" ]
  pull_request:
    branches: [ "action/pack" ]

jobs:
  nuget_desktop:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Nuget Ursa
        run: dotnet pack ./src/Ursa -o ./nugets

      - name: Nuget Ursa.Themes.Semi
        run: dotnet pack ./src/Ursa.Themes.Semi -o ./nugets

      - name: Desktop
        run: dotnet publish ./demo/Ursa.Demo.Desktop -r win-x64 -c Release /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true --self-contained true

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: nuget_desktop
          path: |
            ./nugets
            ./**/publish/*.exe

  android:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: CD Android
        run: cd ./demo/Ursa.Demo.Android

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet publish ./demo/Ursa.Demo.Android -c Release -f net8.0-android --no-restore

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: android
          path: ./**/publish/*Signed.apk
